if(EXISTS "/home/runner/ChartreuseIvoryDisassembly/tests[1]_tests.cmake")
  include("/home/runner/ChartreuseIvoryDisassembly/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
