if(EXISTS "/Users/nacho/Desktop/code/testWordle/Wordle-/tests[1]_tests.cmake")
  include("/Users/nacho/Desktop/code/testWordle/Wordle-/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
